services:
  # assistant:
  #   container_name: assistant
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.assistant
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - SERVER_URL=http://server:5000/api
  #   networks:
  #     - report-network
  #   depends_on:
  #     - server

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "5000:5000"
    networks:
      - report-network

networks:
  report-network:
    driver: bridge
