FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install hf_xet

COPY .env .
COPY . .

ENV GRADIO_SERVER_NAME="0.0.0.0"

CMD ["python3", "main.py"]
